stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - ${preprocess.reviews_dir}
    params:
      - preprocess
    outs:
      - ${preprocess.output}

  split:
    cmd: python scripts/split.py
    deps:
      - scripts/split.py
      - ${split.input}
    params:
      - split
    outs:
      - ${split.train_output}
      - ${split.test_output}

  clean_text:
    cmd: python scripts/clean_text.py
    deps:
      - scripts/clean_text.py
      - ${clean_text.input_train}
      - ${clean_text.input_test}
    params:
      - clean_text
    outs:
      - ${clean_text.train_output}
      - ${clean_text.test_output}

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - ${train.input_train}
      - ${train.input_test}
    params:
      - train
    outs:
      - ${train.models_dir}
    metrics:
      - ${train.output}:
          cache: false

  execute_eda_raw:
    cmd: papermill notebooks/eda_raw.ipynb data/notebooks/eda_raw_executed.ipynb --cwd
      $(pwd)
    deps:
      - notebooks/eda_raw.ipynb
      - data/raw
    outs:
      - data/notebooks/eda_raw_executed.ipynb:
          cache: false

  execute_eda:
    cmd: papermill notebooks/eda.ipynb data/notebooks/eda_executed.ipynb --cwd $(pwd)
    deps:
      - notebooks/eda.ipynb
      - data/processed/reviews.csv
    outs:
      - data/notebooks/eda_executed.ipynb:
          cache: false
