stages:
  preprocess:
    cmd: python scripts/preprocess.py
    deps:
      - scripts/preprocess.py
      - ${preprocess.reviews_dir}
    params:
      - preprocess
    outs:
      - ${preprocess.output}

  split:
    cmd: python scripts/split.py
    deps:
      - scripts/split.py
      - ${split.input}
    params:
      - split
    outs:
      - ${split.train_output}
      - ${split.test_output}

  clean_text:
    cmd: python scripts/clean_text.py
    deps:
      - scripts/clean_text.py
      - ${clean_text.input_train}
      - ${clean_text.input_test}
    params:
      - clean_text
    outs:
      - ${clean_text.train_output}
      - ${clean_text.test_output}

  train:
    cmd: python scripts/train.py
    deps:
      - scripts/train.py
      - ${train.input_train}
      - ${train.input_test}
    params:
      - train
    outs:
      - ${train.models_dir}
    metrics:
      - ${train.output}:
          cache: false
